import { readdir, readFile } from "node:fs/promises";
import { resolve } from "node:path";
import postgres from "postgres";
import { config } from "../config.js";

/**
 * Provisions a new tenant schema by:
 * 1. Creating the PostgreSQL schema `tenant_{id}`
 * 2. Applying all tenant migration files in order
 * 3. Creating a migration tracking table to support incremental migrations
 *
 * Tenant migrations are generated by drizzle-kit into `src/db/migrations/tenant/`.
 * Since tenant tables use pgTable() (unqualified names), the SQL references
 * `"public"."table"` in FK constraints. We replace those with unqualified
 * references so they resolve within the tenant schema via search_path.
 */

const TENANT_MIGRATIONS_DIR = resolve(
  import.meta.dirname,
  "../db/migrations/tenant",
);

/**
 * Read and sort all .sql migration files from the tenant migrations directory.
 */
async function getMigrationFiles(): Promise<
  Array<{ name: string; sql: string }>
> {
  const files = await readdir(TENANT_MIGRATIONS_DIR);
  const sqlFiles = files.filter((f) => f.endsWith(".sql")).sort();

  const migrations = await Promise.all(
    sqlFiles.map(async (name) => {
      const content = await readFile(
        resolve(TENANT_MIGRATIONS_DIR, name),
        "utf-8",
      );
      return { name, sql: content };
    }),
  );

  return migrations;
}

/**
 * Transform tenant migration SQL so FK references resolve within the
 * tenant schema instead of pointing to `public`.
 *
 * drizzle-kit generates: REFERENCES "public"."companies"("id")
 * We need:               REFERENCES "companies"("id")
 */
function fixSchemaReferences(sql: string): string {
  return sql.replace(/REFERENCES "public"\./g, "REFERENCES ");
}

/**
 * Provision a new tenant schema with all migrations applied.
 *
 * @param schemaName - The schema name, e.g. "tenant_a1b2c3d4-e5f6-..."
 * @throws If schema already exists or migration fails
 */
export async function provisionTenantSchema(
  schemaName: string,
): Promise<void> {
  if (!/^tenant_[a-f0-9-]+$/.test(schemaName)) {
    throw new Error(
      `Invalid tenant schema name: ${schemaName}. Must match tenant_{uuid}`,
    );
  }

  const sql = postgres(config.database.url);

  try {
    // Create the schema
    await sql.unsafe(`CREATE SCHEMA "${schemaName}"`);

    // Set search_path so all table creation happens in the tenant schema
    await sql.unsafe(`SET search_path TO "${schemaName}"`);

    // Create migration tracking table
    await sql.unsafe(`
      CREATE TABLE "_drizzle_migrations" (
        id SERIAL PRIMARY KEY,
        migration_name VARCHAR(255) NOT NULL UNIQUE,
        applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    // Read and apply all migrations
    const migrations = await getMigrationFiles();

    for (const migration of migrations) {
      // Split on drizzle's statement breakpoints
      const statements = migration.sql
        .split("--> statement-breakpoint")
        .map((s) => s.trim())
        .filter((s) => s.length > 0);

      for (const statement of statements) {
        const fixed = fixSchemaReferences(statement);
        await sql.unsafe(fixed);
      }

      // Record the migration
      await sql.unsafe(
        `INSERT INTO "_drizzle_migrations" (migration_name) VALUES ($1)`,
        [migration.name],
      );
    }
  } finally {
    await sql.end();
  }
}

/**
 * Apply any pending tenant migrations to an existing tenant schema.
 * Compares migration files against the tracking table and applies only new ones.
 */
export async function migrateTenantSchema(schemaName: string): Promise<void> {
  if (!/^tenant_[a-f0-9-]+$/.test(schemaName)) {
    throw new Error(
      `Invalid tenant schema name: ${schemaName}. Must match tenant_{uuid}`,
    );
  }

  const sql = postgres(config.database.url);

  try {
    await sql.unsafe(`SET search_path TO "${schemaName}"`);

    // Get already-applied migrations
    const applied = await sql.unsafe<Array<{ migration_name: string }>>(
      `SELECT migration_name FROM "_drizzle_migrations" ORDER BY id`,
    );
    const appliedSet = new Set(applied.map((r) => r.migration_name));

    // Get all migration files
    const migrations = await getMigrationFiles();
    const pending = migrations.filter((m) => !appliedSet.has(m.name));

    if (pending.length === 0) {
      return;
    }

    for (const migration of pending) {
      const statements = migration.sql
        .split("--> statement-breakpoint")
        .map((s) => s.trim())
        .filter((s) => s.length > 0);

      for (const statement of statements) {
        const fixed = fixSchemaReferences(statement);
        await sql.unsafe(fixed);
      }

      await sql.unsafe(
        `INSERT INTO "_drizzle_migrations" (migration_name) VALUES ($1)`,
        [migration.name],
      );
    }
  } finally {
    await sql.end();
  }
}

/**
 * Apply pending migrations to ALL active tenant schemas.
 * Reads tenant list from public.tenants table.
 */
export async function migrateAllTenants(): Promise<void> {
  const sql = postgres(config.database.url);

  try {
    const rows = await sql.unsafe<Array<{ schema_name: string }>>(
      `SELECT schema_name FROM public.tenants WHERE status = 'active'`,
    );

    for (const row of rows) {
      await migrateTenantSchema(row.schema_name);
    }
  } finally {
    await sql.end();
  }
}
