import { useState } from "react";
import { Link } from "react-router";
import { FileText, Plus, Search } from "lucide-react";
import { useBillingRuns } from "@frontend/api/billing-runs.js";
import type { BillingRunListParams } from "@frontend/api/billing-runs.js";
import { Button } from "@frontend/components/ui/button.js";
import { Input } from "@frontend/components/ui/input.js";
import { Badge } from "@frontend/components/ui/badge.js";
import {
  Card,
  CardContent,
  CardHeader,
} from "@frontend/components/ui/card.js";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@frontend/components/ui/table.js";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@frontend/components/ui/select.js";
import { Skeleton } from "@frontend/components/ui/skeleton.js";

const STATUS_VARIANTS: Record<string, "default" | "secondary" | "destructive" | "outline"> = {
  pending: "outline",
  generating: "secondary",
  generated: "default",
  completed: "default",
  failed: "destructive",
};

const STATUS_LABELS: Record<string, string> = {
  pending: "Pending",
  generating: "Generating",
  generated: "Generated",
  completed: "Completed",
  failed: "Failed",
};

function formatCurrency(val: string | null): string {
  if (!val) return "$0.00";
  const n = parseFloat(val);
  return isNaN(n) ? "$0.00" : `$${n.toLocaleString("en-AU", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

function formatDate(dateStr: string): string {
  const d = new Date(dateStr);
  return d.toLocaleDateString("en-AU", { day: "2-digit", month: "2-digit", year: "numeric" });
}

export function BillingRunsPage(): React.JSX.Element {
  const [search, setSearch] = useState("");
  const [statusFilter, setStatusFilter] = useState<string>("");

  const params: BillingRunListParams = {};
  if (search) params.search = search;
  if (statusFilter && statusFilter !== "all") params.status = statusFilter;

  const { data, isLoading } = useBillingRuns(params);

  const runs = data?.data ?? [];

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-semibold tracking-tight">Billing Runs</h1>
          <p className="text-sm text-muted-foreground">
            Batch invoice generation and management
          </p>
        </div>
        <Button asChild>
          <Link to="/billing-runs/new">
            <Plus className="mr-2 h-4 w-4" />
            New Billing Run
          </Link>
        </Button>
      </div>

      {/* Filters */}
      <Card>
        <CardHeader>
          <div className="flex items-center gap-4">
            <div className="relative flex-1">
              <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
              <Input
                placeholder="Search billing runs..."
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                className="pl-9"
              />
            </div>
            <Select value={statusFilter} onValueChange={setStatusFilter}>
              <SelectTrigger className="w-[180px]">
                <SelectValue placeholder="All statuses" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All statuses</SelectItem>
                <SelectItem value="pending">Pending</SelectItem>
                <SelectItem value="generating">Generating</SelectItem>
                <SelectItem value="generated">Generated</SelectItem>
                <SelectItem value="completed">Completed</SelectItem>
                <SelectItem value="failed">Failed</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </CardHeader>
        <CardContent>
          {isLoading ? (
            <div className="space-y-2">
              {Array.from({ length: 5 }).map((_, i) => (
                <Skeleton key={i} className="h-12 w-full" />
              ))}
            </div>
          ) : runs.length === 0 ? (
            <div className="py-8 text-center text-muted-foreground">
              <FileText className="mx-auto mb-2 h-8 w-8 opacity-50" />
              <p>No billing runs found</p>
            </div>
          ) : (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Run #</TableHead>
                  <TableHead>Period</TableHead>
                  <TableHead>Status</TableHead>
                  <TableHead className="text-right">Invoices</TableHead>
                  <TableHead className="text-right">Total Amount</TableHead>
                  <TableHead>Generated By</TableHead>
                  <TableHead>Created</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {runs.map((run) => (
                  <TableRow key={run.id}>
                    <TableCell>
                      <Link
                        to={`/billing-runs/${run.id}`}
                        className="font-medium text-primary hover:underline"
                      >
                        {run.runNumber}
                      </Link>
                    </TableCell>
                    <TableCell>
                      {formatDate(run.periodStart)} -- {formatDate(run.periodEnd)}
                    </TableCell>
                    <TableCell>
                      <Badge variant={STATUS_VARIANTS[run.status] ?? "secondary"}>
                        {STATUS_LABELS[run.status] ?? run.status}
                      </Badge>
                    </TableCell>
                    <TableCell className="text-right">{run.invoiceCount}</TableCell>
                    <TableCell className="text-right font-mono">
                      {formatCurrency(run.totalAmount)}
                    </TableCell>
                    <TableCell>{run.generatedByName ?? "--"}</TableCell>
                    <TableCell>{formatDate(run.createdAt)}</TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          )}
        </CardContent>
      </Card>

      {data && (
        <div className="text-xs text-muted-foreground">
          Showing {runs.length} of {data.total ?? runs.length} billing runs
        </div>
      )}
    </div>
  );
}
